"use client";
import { useEffect, useMemo, useState } from "react";
import { authHeaders, supabase } from "@/lib/supabase-browser";

type U={id:string;email?:string;emailConfirmed:boolean;role:"user"|"admin";approved:boolean;createdAt:string;lastSignInAt?:string|null};
type Tab="overview"|"users"|"system";
export default function AdminPage(){
 const [users,setUsers]=useState<U[]>([]),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[error,setError]=useState(""),[ready,setReady]=useState(false),[loading,setLoading]=useState(true),[tab,setTab]=useState<Tab>("overview"),[query,setQuery]=useState("");
 async function load(){setLoading(true);const r=await fetch("/api/admin/users",{headers:await authHeaders()});if(!r.ok){setReady(false);setLoading(false);return false;}const d=await r.json();setUsers(d.users);setReady(true);setLoading(false);return true;}
 useEffect(()=>{void load()},[]);
 async function login(e:React.FormEvent){e.preventDefault();setError("");if(!supabase)return;const {error}=await supabase.auth.signInWithPassword({email,password});if(error){setError("פרטי הכניסה אינם נכונים.");return;}if(!await load())setError("החשבון אינו מורשה לממשק הניהול.");}
 async function update(u:U,body:object){setError("");const r=await fetch("/api/admin/users",{method:"PATCH",headers:{...(await authHeaders()),"Content-Type":"application/json"},body:JSON.stringify({userId:u.id,...body})});if(!r.ok){const d=await r.json().catch(()=>null);setError(d?.error??"העדכון נכשל.");return;}await load();}
 async function logout(){await supabase?.auth.signOut();setReady(false);setUsers([]);}
 const stats=useMemo(()=>({all:users.length,approved:users.filter(x=>x.approved).length,pending:users.filter(x=>!x.approved).length,active:users.filter(x=>x.lastSignInAt).length}),[users]);
 const filtered=users.filter(u=>(u.email??"").toLowerCase().includes(query.toLowerCase()));
 if(loading&&!ready)return <main className="welcome"><div className="brand-mark">מ׳</div><p>טוען ממשק ניהול…</p></main>;
 if(!ready)return <main className="welcome"><div className="brand-mark">מ׳</div><p className="eyebrow">CONTROL ROOM</p><h1>כניסת מנהל</h1><form className="panel stack" onSubmit={login}><label>אימייל<input type="email" dir="ltr" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>סיסמה<input type="password" dir="ltr" required value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="primary">כניסה</button>{error&&<p className="error">{error}</p>}</form></main>;
 return <main className="onboarding" style={{paddingBottom:96}}><header className="row" style={{justifyContent:"space-between",alignItems:"center"}}><div><p className="eyebrow">מה שכחתי? · CONTROL ROOM</p><h1 style={{marginBottom:4}}>ניהול מערכת</h1></div><button className="secondary" onClick={logout}>יציאה</button></header>
 <nav className="row" style={{position:"sticky",top:0,zIndex:5,padding:"10px 0",background:"var(--background, #faf7f4)",overflowX:"auto"}}><button className={tab==="overview"?"primary":"secondary"} onClick={()=>setTab("overview")}>סקירה</button><button className={tab==="users"?"primary":"secondary"} onClick={()=>setTab("users")}>משתמשים {stats.pending?`(${stats.pending})`:""}</button><button className={tab==="system"?"primary":"secondary"} onClick={()=>setTab("system")}>מערכת</button></nav>
 {tab==="overview"&&<><section className="panel"><h2>תמונת מצב</h2><div style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:10}}><Stat n={stats.all} t="משתמשים"/><Stat n={stats.approved} t="מאושרים"/><Stat n={stats.pending} t="ממתינים"/><Stat n={stats.active} t="נכנסו למערכת"/></div></section>{stats.pending>0&&<section className="panel stack"><h2>דורש טיפול</h2><p>{stats.pending} משתמשים ממתינים לאישור.</p><button className="primary" onClick={()=>setTab("users")}>לעבור לאישורים</button></section>}<section className="panel stack"><h2>גישה מהירה</h2><button className="secondary" onClick={()=>setTab("users")}>ניהול משתמשים והרשאות</button><button className="secondary" onClick={()=>setTab("system")}>מצב מערכת וחיבורים</button></section></>}
 {tab==="users"&&<section className="panel stack"><div className="row" style={{justifyContent:"space-between"}}><h2>משתמשים</h2><button className="secondary" onClick={()=>load()}>רענון</button></div><input placeholder="חיפוש לפי אימייל" dir="ltr" value={query} onChange={e=>setQuery(e.target.value)}/>{filtered.map(u=><article key={u.id} className="panel stack"><strong dir="ltr">{u.email}</strong><p>{u.role==="admin"?"מנהל":"משתמש"} · {u.approved?"מאושר":"ממתין לאישור"} · {u.emailConfirmed?"מייל מאושר":"מייל לא מאושר"}</p>{u.lastSignInAt&&<small>כניסה אחרונה: {new Date(u.lastSignInAt).toLocaleString("he-IL")}</small>}<div className="row" style={{flexWrap:"wrap"}}>{!u.approved&&<button className="primary" onClick={()=>update(u,{approved:true,confirmEmail:true})}>אישור משתמש</button>}{u.approved&&u.role!=="admin"&&<button className="secondary" onClick={()=>update(u,{approved:false})}>חסימה</button>}<button className="secondary" onClick={()=>update(u,{role:u.role==="admin"?"user":"admin"})}>{u.role==="admin"?"הסרת Admin":"הפוך ל-Admin"}</button></div></article>)}</section>}
 {tab==="system"&&<section className="panel stack"><h2>מצב מערכת</h2><p>Supabase · מחובר</p><p>Authentication · פעיל</p><p>הרשאות מנהל · פעילות</p><p>אישור משתמשים · פעיל</p><button className="secondary" onClick={()=>load()}>בדיקת חיבור מחדש</button></section>}{error&&<p className="error">{error}</p>}</main>;
}
function Stat({n,t}:{n:number;t:string}){return <div className="panel" style={{margin:0,padding:14}}><strong style={{fontSize:28}}>{n}</strong><p style={{margin:0}}>{t}</p></div>}
