-- Reconstructs the production access-control and analytics layer after database/schema.sql.
begin;
create table if not exists public.user_roles(
 user_id uuid primary key references auth.users(id) on delete cascade,
 role text not null default 'user' check(role in('user','admin')),
 approved boolean not null default false,
 created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
alter table public.user_roles enable row level security;
create or replace function public.is_admin(uid uuid default auth.uid()) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.user_roles r where r.user_id=uid and r.role='admin' and r.approved=true); $$;
create or replace function public.is_approved(uid uuid default auth.uid()) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.user_roles r where r.user_id=uid and r.approved=true); $$;
revoke all on function public.is_admin(uuid),public.is_approved(uuid) from public,anon;
grant execute on function public.is_admin(uuid),public.is_approved(uuid) to authenticated,service_role;
drop policy if exists users_read_own_role on public.user_roles;
create policy users_read_own_role on public.user_roles for select to authenticated using(user_id=auth.uid());
drop policy if exists admins_read_roles on public.user_roles;
create policy admins_read_roles on public.user_roles for select to authenticated using(public.is_admin(auth.uid()));
drop policy if exists admins_update_roles on public.user_roles;
create policy admins_update_roles on public.user_roles for update to authenticated using(public.is_admin(auth.uid())) with check(public.is_admin(auth.uid()));
-- New signups are pending normal users. The first admin is bootstrapped explicitly
-- by an operator/service-role action; no personal email is encoded in schema.
create or replace function public.handle_new_user_role() returns trigger language plpgsql security definer set search_path='' as $$ begin insert into public.user_roles(user_id,role,approved) values(new.id,'user',false) on conflict(user_id) do nothing; return new; end; $$;
drop trigger if exists on_auth_user_created_role on auth.users;
create trigger on_auth_user_created_role after insert on auth.users for each row execute function public.handle_new_user_role();
create table if not exists public.activity_events(id bigint generated by default as identity primary key,owner_id uuid references auth.users(id) on delete set null,event_type text not null,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create index if not exists activity_events_created_at_idx on public.activity_events(created_at desc);
create index if not exists activity_events_owner_idx on public.activity_events(owner_id,created_at desc);
alter table public.activity_events enable row level security;
drop policy if exists owners_read_activity on public.activity_events;
create policy owners_read_activity on public.activity_events for select to authenticated using(owner_id=auth.uid());
grant select on public.activity_events to authenticated; grant all on public.activity_events to service_role;
-- Approval is enforced in the database as well as in server routes.
drop policy if exists own_state on public.app_states;
create policy own_state on public.app_states for all to authenticated using(auth.uid()=owner_id and public.is_approved(auth.uid())) with check(auth.uid()=owner_id and public.is_approved(auth.uid()));
drop policy if exists own_push on public.push_subscriptions;
create policy own_push on public.push_subscriptions for all to authenticated using(auth.uid()=owner_id and public.is_approved(auth.uid())) with check(auth.uid()=owner_id and public.is_approved(auth.uid()));
drop policy if exists own_reminders on public.reminder_queue;
create policy own_reminders on public.reminder_queue for all to authenticated using(auth.uid()=owner_id and public.is_approved(auth.uid())) with check(auth.uid()=owner_id and public.is_approved(auth.uid()));
commit;
