export const ERROR_CODES = [
  "revision_conflict",
  "ai_timeout",
  "ai_network",
  "ai_invalid_output",
  "ai_invalid_json",
  "ai_empty",
  "ai_incomplete",
  "ai_insufficient_quota",
  "ai_rate_limited",
  "ai_configuration",
  "ai_upstream",
  "ai_consent_required",
  "ai_not_configured",
  "ai_failed",
  "chat_idempotency_conflict",
  "chat_turn_in_progress",
  "chat_receipt_unavailable",
  "chat_receipt_write_failed",
  "chat_claim_invalid",
  "proposal_expired",
  "proposal_not_found",
  "proposal_not_pending",
  "proposal_empty_after_revalidate",
  "proposals_read_failed",
  "proposals_write_failed",
  "proposals_update_failed",
  "action_idempotency_conflict",
  "state_save_failed",
  "state_read_failed",
  "auth_required",
  "session_expired",
  "account_not_approved",
  "cloud_not_configured",
  "backend_not_configured",
  "invalid_input",
  "invalid_json",
  "missing_body",
  "payload_too_large",
  "hourly_limit",
  "budget_unavailable",
  "reminder_read_failed",
  "microphone_denied",
  "microphone_unavailable",
  "microphone_busy",
  "microphone_unsupported",
  "microphone_insecure_context",
  "microphone_failed",
  "notification_denied",
  "notification_unsupported",
  "transcription_failed",
  "transcription_consent_required",
  "transcription_not_configured",
  "scan_analysis_failed",
  "recording_unsupported",
  "request_failed",
  "client_upgrade_required",
  "internal_error",
] as const;

export type ErrorCode = (typeof ERROR_CODES)[number];

/** Canonical Hebrew messages for UI mapping. Server may still send message text. */
export const ERROR_MESSAGES_HE: Record<ErrorCode, string> = {
  revision_conflict: "המידע השתנה בחלון אחר. טענו מחדש לפני ניסיון נוסף.",
  ai_timeout: "הסוכן לא הצליח לענות בזמן. לא בוצעו שינויים; אפשר לנסות שוב.",
  ai_network: "תקלת רשת מול הסוכן. לא בוצעו שינויים; אפשר לנסות שוב.",
  ai_invalid_output: "התשובה מהסוכן לא הייתה תקינה. לא בוצעו שינויים.",
  ai_invalid_json: "התשובה מהסוכן לא הייתה תקינה. לא בוצעו שינויים.",
  ai_empty: "הסוכן לא החזיר תשובה. לא בוצעו שינויים.",
  ai_incomplete: "התשובה לא הושלמה. לא בוצעו שינויים; אפשר לנסות שוב.",
  ai_insufficient_quota:
    "מכסת ה-AI הסתיימה כרגע. לא בוצעו שינויים; אפשר להמשיך ידנית או לנסות לאחר חידוש הקרדיט.",
  ai_rate_limited:
    "שירות ה-AI עמוס כרגע. לא בוצעו שינויים; אפשר לנסות שוב בעוד רגע.",
  ai_configuration: "חיבור ה-AI דורש תיקון בהגדרות השרת. לא בוצעו שינויים.",
  ai_upstream: "הסוכן לא הצליח לענות כרגע. לא בוצעו שינויים; אפשר לנסות שוב.",
  ai_consent_required:
    "אפשר להפעיל עזרה אישית בהגדרות, לאחר הסכמה לשימוש במידע.",
  ai_not_configured: "הסוכן עדיין לא מחובר. אפשר להוסיף ולנהל משימות ידנית.",
  ai_failed: "הסוכן לא הצליח לענות כרגע.",
  chat_idempotency_conflict: "מזהה ניסיון השיחה כבר שייך להודעה אחרת.",
  chat_turn_in_progress:
    "אותו ניסיון שיחה עדיין בעיבוד. אפשר להמתין רגע ולנסות שוב.",
  chat_receipt_unavailable:
    "לא ניתן לבדוק ניסיון שיחה קודם. אפשר לנסות שוב בעוד רגע.",
  chat_receipt_write_failed:
    "השיחה עובדה אך שמירת האישור נכשלה. אפשר לנסות שוב באותו מפתח.",
  chat_claim_invalid: "תשובת claim לא תקינה.",
  proposal_expired: "פג תוקף ההצעה.",
  proposal_not_found: "ההצעה לא נמצאה.",
  proposal_not_pending: "ההצעה אינה ממתינה לאישור.",
  proposal_empty_after_revalidate: "אין פעולות תקפות לאישור מול המצב העדכני.",
  proposals_read_failed: "לא ניתן לקרוא הצעות ממתינות.",
  proposals_write_failed: "לא ניתן לשמור הצעה.",
  proposals_update_failed: "לא ניתן לעדכן הצעה.",
  action_idempotency_conflict: "מזהה ניסיון השמירה כבר שייך לפעולה אחרת.",
  state_save_failed: "השמירה לא הצליחה. השינוי עדיין לא נשמר.",
  state_read_failed: "לא ניתן לקרוא את המידע בענן.",
  auth_required: "צריך להתחבר כדי להמשיך.",
  session_expired: "ההתחברות הסתיימה. יש להתחבר שוב.",
  account_not_approved: "החשבון ממתין לאישור מנהל.",
  cloud_not_configured: "שמירה בענן עדיין לא מחוברת.",
  backend_not_configured: "שירות הרקע עדיין לא הוגדר.",
  invalid_input: "המידע שנשלח אינו תקין.",
  invalid_json: "הבקשה אינה תקינה.",
  missing_body: "חסר תוכן.",
  payload_too_large: "הבקשה גדולה מדי.",
  hourly_limit:
    "הגענו למכסת הבקשות לשעה. אפשר להמשיך לנהל משימות ולנסות שוב בהמשך.",
  budget_unavailable: "בקרת השימוש אינה זמינה.",
  reminder_read_failed: "לא ניתן לקרוא את מצב התזכורות.",
  microphone_denied:
    "לא ניתנה גישה למיקרופון. אפשר לשנות בהגדרות הדפדפן או להקליד.",
  microphone_unavailable: "לא נמצא מיקרופון זמין במכשיר.",
  microphone_busy: "המיקרופון תפוס כרגע באפליקציה אחרת.",
  microphone_unsupported: "הדפדפן או המכשיר לא תומכים במיקרופון כאן.",
  microphone_insecure_context:
    "צריך לפתוח את האפליקציה בכתובת מאובטחת (HTTPS) כדי לאשר מיקרופון.",
  microphone_failed: "לא הצלחנו לבקש גישה למיקרופון. אפשר לנסות שוב.",
  notification_denied:
    "התראות חסומות בדפדפן. אפשר לאפשר אותן מחדש בהרשאות האתר.",
  notification_unsupported: "הדפדפן הזה לא תומך בהתראות.",
  transcription_failed: "לא הצלחתי לתמלל. אפשר לנסות שוב או להקליד.",
  transcription_consent_required: "נדרשת הסכמה לשימוש בשירות התמלול.",
  transcription_not_configured: "התמלול עדיין לא מחובר. אפשר להקליד.",
  scan_analysis_failed: "הסקירה שלך נשמרה, אבל לא הצלחתי לנתח אותה כרגע.",
  recording_unsupported: "הדפדפן הזה לא מאפשר הקלטה.",
  request_failed: "הפעולה לא הושלמה. אפשר לנסות שוב.",
  client_upgrade_required: "צריך לרענן את האפליקציה כדי להמשיך.",
  internal_error: "הפעולה לא הושלמה. אפשר לנסות שוב.",
};

export function messageForCode(code: string, fallback?: string) {
  return (
    ERROR_MESSAGES_HE[code as ErrorCode] ??
    fallback ??
    ERROR_MESSAGES_HE.internal_error
  );
}
